/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[podcast_slug]/': RouteRecordInfo<
      '/[podcast_slug]/',
      '/:podcast_slug',
      { podcast_slug: ParamValue<true> },
      { podcast_slug: ParamValue<false> },
      | never
    >,
    '/[podcast_slug]/episode/[slug]': RouteRecordInfo<
      '/[podcast_slug]/episode/[slug]',
      '/:podcast_slug/episode/:slug',
      { podcast_slug: ParamValue<true>, slug: ParamValue<true> },
      { podcast_slug: ParamValue<false>, slug: ParamValue<false> },
      | never
    >,
    '/[podcast_slug]/post/[slug]': RouteRecordInfo<
      '/[podcast_slug]/post/[slug]',
      '/:podcast_slug/post/:slug',
      { podcast_slug: ParamValue<true>, slug: ParamValue<true> },
      { podcast_slug: ParamValue<false>, slug: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[podcast_slug]/index.vue': {
      routes:
        | '/[podcast_slug]/'
      views:
        | never
    }
    'src/pages/[podcast_slug]/episode/[slug].vue': {
      routes:
        | '/[podcast_slug]/episode/[slug]'
      views:
        | never
    }
    'src/pages/[podcast_slug]/post/[slug].vue': {
      routes:
        | '/[podcast_slug]/post/[slug]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
