#!/usr/bin/env bash

set -e

SCRIPT_PATH="$(dirname "${BASH_SOURCE[0]}")"
# shellcheck disable=SC1091
. "${SCRIPT_PATH}/../.env"
ember deploy production
# shellcheck disable=SC2029
ssh "${SSH_USERNAME}"@"${SSH_HOST}" cd "${SSH_PATH}" && npm i && sudo systemctl restart podcast-frontend.service
