#!/usr/bin/env bash
# shellcheck disable=SC2029,SC1091

set -e

SCRIPT_PATH="$(dirname "${BASH_SOURCE[0]}")"
. "${SCRIPT_PATH}/../.env"
ssh "${SSH_USERNAME}@${SSH_HOST}" "mkdir -p \"${SSH_DIST_PATH}\""
scp "${SCRIPT_PATH}/../deployment"/* "${SSH_USERNAME}@${SSH_HOST}:${SSH_PATH}/"
ssh "${SSH_USERNAME}@${SSH_HOST}" "cd \"${SSH_PATH}\" && npm i fastboot-app-server"
ember deploy production
ssh "${SSH_USERNAME}"@"${SSH_HOST}" "cd \"${SSH_DIST_PATH}\" && npm i && sudo systemctl restart spodcat-frontend.service"
